export const EVENTS = {
  PIECE_COLLISION: "piece:collision",
  BOARD_COMPLETED_ROWS: "board:completedRows",
  BOARD_DELETED_ROWS: "board:deletedRows",
  GAME_START: "game:start",
  GAME_STARTED: "game:started",
  GAME_PAUSED: "game:paused",
  GAME_OVER: "game:over",
  GAME_RESET: "game:reset",
  GAME_UPDATED: "game:updated",
  SCORE_UPDATED: "score:updated",
  INPUT_LEFT: "input:left",
  INPUT_RIGHT: "input:right",
  INPUT_DOWN: "input:down",
  INPUT_ROTATE: "input:rotate",
  INPUT_PAUSE: "input:pause",
};
